### ISSUE TITLE
Download CV bug: no file downloaded

### ISSUE THREAD

**Issue by Brun0-Link** [cristian-sbardelotto/portfolio#15]
Alo Cristian, seu portfolio é íncrível! Tentei baixar o CV pra me inspirar, mas percebi que o diretório do PDF está incorreto. Parece que anteriormente ele se encontrava em assets, porém agora está em documents, portanto resolveria ajustar a URL do button.

**Comment by cristian-sbardelotto** [comment]
Agradeço profundamente por ter aberto essa Issue, Bruno!
Realmente, era algo que eu não tinha percebido.
O problema foi corrigido, pode-se ver no commit https://github.com/cristian-sbardelotto/portfolio/commit/5a7a55ccdc232a1c2f53b63de682fc9005deb271, e agora já imagino que tudo voltou aos conformes.
Novamente, agradeço pela contribuição. 🚀
@Brun0-Link
